# Le port sur lequel est lancee l'application web
server.port=${PORT:8080}

# Encodage des scripts sql d'initialisation de la BD
spring.sql.init.encoding=UTF-8

# Base de donnees PostgreSQL sur Render (URL EXTERNE)
spring.datasource.url=jdbc:postgresql://dpg-d6auihpr0fns73fdidn0-a.frankfurt-postgres.render.com:5432/medicaments
spring.datasource.username=medicaments_user
spring.datasource.password=NyPs4R6DDOWEVbPJs95FMXn6gLeGDisS
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate garde les tables sans les recreer
spring.jpa.hibernate.ddl-auto=update

# On initialise la BD apres la creation du schema
spring.jpa.defer-datasource-initialization=true

# Ressources statiques
spring.web.resources.static-locations=classpath:/static/,file:/tmp

# Affichage des erreurs
server.error.whitelabel.enabled=true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Configuration JSON
spring.data.rest.defaultMediaType=application/json
spring.jackson.serialization.indent-output=true

# Base path de l'API REST
spring.data.rest.base-path=api

# Proxy
server.forward-headers-strategy=native

# Logs
server.error.include-stacktrace=never
logging.level.web=DEBUG
spring.mvc.log-request-details=true
logging.level.org.springframework=INFO
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=false
logging.level.org.hibernate.type=ERROR
logging.level.pharmacie=DEBUG
logging.pattern.console=%clr(%-5p)  %cyan(%logger{15}) - %msg %n

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Upload de fichiers
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

# Postmark (NOUVEAU TOKEN ET EMAIL SENDER)
postmark.api.token=510674fb-5eaa-457d-8231-34ecfe3b4e6a
postmark.sender.email=lina.ouazzani_chahdi@etud.univ-jfc.fr